### PR TITLE
db/pebbledb: make WriteTx.Discard safe to call again

### LINKED ISSUE #1139: datarace on pebble with statedb (testing)
```
WARNING: DATA RACE
Write at 0x00c0009ac038 by goroutine 401:
  github.com/cockroachdb/pebble.newIndexedBatch()
      /home/runner/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20230620232302-06034ff014e0/batch.go:371 +0x1a4
  github.com/cockroachdb/pebble.(*DB).NewIndexedBatch()
      /home/runner/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20230620232302-06034ff014e0/db.go:1424 +0x7a
  go.vocdoni.io/dvote/db/pebbledb.(*PebbleDB).WriteTx()
      /home/runner/work/vocdoni-node/vocdoni-node/db/pebbledb/pebledb.go:138 +0x25
  go.vocdoni.io/dvote/statedb.(*StateDB).BeginTx()
      /home/runner/work/vocdoni-node/vocdoni-node/statedb/statedb.go:301 +0xc5
  go.vocdoni.io/dvote/vochain/state.NewState()
      /home/runner/work/vocdoni-node/vocdoni-node/vochain/state/state.go:124 +0x311
  go.vocdoni.io/dvote/test/testcommon.NewVochainState()
      /home/runner/work/vocdoni-node/vocdoni-node/test/testcommon/vochain.go:86 +0x4f
  go.vocdoni.io/dvote/test/testcommon.NewVochainStateWithProcess()
      /home/runner/work/vocdoni-node/vocdoni-node/test/testcommon/vochain.go:129 +0x34
  go.vocdoni.io/dvote/test.TestCountVotes()
      /home/runner/work/vocdoni-node/vocdoni-node/test/statedb_test.go:112 +0x4f
  testing.tRunner()
      /opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:1595 +0x238
  testing.(*T).Run.func1()
      /opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:1648 +0x44

Previous read at 0x00c0009ac038 by goroutine 395:
  github.com/cockroachdb/pebble.(*Batch).release()
      /home/runner/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20230620232302-06034ff014e0/batch.go:388 +0x3c
  github.com/cockroachdb/pebble.(*Batch).Close()
      /home/runner/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20230620232302-06034ff014e0/batch.go:1283 +0x26
  go.vocdoni.io/dvote/db/pebbledb.WriteTx.Discard()
      /home/runner/work/vocdoni-node/vocdoni-node/db/pebbledb/pebledb.go:96 +0xe
  go.vocdoni.io/dvote/db/prefixeddb.(*PrefixedWriteTx).Discard()
      /home/runner/work/vocdoni-node/vocdoni-node/db/prefixeddb/prefixeddb.go:129 +0x42
  go.vocdoni.io/dvote/vochain/state.(*State).Close()
      /home/runner/work/vocdoni-node/vocdoni-node/vochain/state/state.go:470 +0xc7
  go.vocdoni.io/dvote/test/testcommon.NewVochainState.func1()
      /home/runner/work/vocdoni-node/vocdoni-node/test/testcommon/vochain.go:90 +0x2e
  testing.(*common).Cleanup.func1()
      /opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:1169 +0x182
  testing.(*common).runCleanup()
      /opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:1[347](https://github.com/vocdoni/vocdoni-node/actions/runs/6470977793/job/17568382973#step:5:348) +0x1c2
  testing.tRunner.func2()
      /opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:1589 +0x50
  runtime.deferreturn()
      /opt/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:477 +0x30
  testing.(*T).Run.func1()
      /opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:1648 +0x44

Goroutine 401 (running) created at:
  testing.(*T).Run()
      /opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:1648 +0x82a
  testing.runTests.func1()
      /opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:2054 +0x84
  testing.tRunner()
      /opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:1595 +0x238
  testing.runTests()
      /opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:2052 +0x896
  testing.(*M).Run()
      /opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:1925 +0xb57
  main.main()
      _testmain.go:103 +0x2e4

Goroutine 395 (running) created at:
  testing.(*T).Run()
      /opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:1648 +0x82a
  testing.runTests.func1()
      /opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:2054 +0x84
  testing.tRunner()
      /opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:1595 +0x238
  testing.runTests()
      /opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:2052 +0x896
  testing.(*M).Run()
      /opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:1925 +0xb57
  main.main()
      _testmain.go:103 +0x2e4
==================
--- FAIL: TestCountVotes (0.03s)
    testing.go:1465: race detected during execution of test
--- FAIL: TestAddValidator (0.04s)
    testing.go:1465: race detected during execution of test
FAIL
```

### PR DESCRIPTION
**Pull request by mvdan**
(see commit message)

### CODE REVIEW

File: db/pebbledb/pebledb.go [hunk 1]
```diff
@@ -61,39 +62,53 @@ func iterate(reader pebble.Reader, prefix []byte, callback func(k, v []byte) boo
...
+		// Silently allow discarding twice or after a commit,
+		// since it can help for the sake of defers.
+		// Note that upstream pebbledb doesn't really allow calling Close twice;
+		// the object gets put in a shared pool, so a later call to Close races
+		// with another goroutine having already reused the same object from the pool.
+		return
+	}
 	// Close returns an error, but here in the Discard context is omitted
 	tx.batch.Close()
+	tx.batch = nil
```
Comment (p4u) [inline db/pebbledb/pebledb.go:111]: Isn't this still racy? Since it is not atomic and there is no lock, two Discard() calls could be done in parallel and the second would call tx.batch.Close() of a nil object.

Comment (mvdan) [reply db/pebbledb/pebledb.go:111]: The race in master is not because of two goroutines calling Discard concurrently on the same tx. We have never supported concurrent calls on the same tx like that, and there's no reason why we should - a single tx is meant to be for a sequence of operations done by a single goroutine.

The race happens when one goroutine grabs one tx (T1) and discards it twice, and another goroutine does the same on another tx (T2). Because pebble uses a global pool of transactions, T1 and T2 might actually be shared after the first discard, since pebble's close method puts the batch back in the pool - so then the second discard can be racy.

Not sure if that made any sense - but the kind of race you mean was never a problem and shouldn't be a problem.

**Review by altergui — APPROVED** [review]

**Comment by altergui** [comment]
job_compose_test failed due to an unrelated reason (CI server issue). fixed it and triggered a re-run

File: db/pebbledb/pebledb.go (hunk 1 above)
Comment (p4u) [reply db/pebbledb/pebledb.go:111]: gotcha
